config/routes.rb
Rails.application.routes.draw do
  resources :products, only: %i[index show]

  namespace :api do
    resources :comments, only: :destroy

    resources :products, only: [] do
      resources :comments, only: :create
    end
  end

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product

  validates :title, presence: true
  validates :description, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached:image

  has_many :comments
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)

    if comment.save
      render json: comment
    else
      render json: { errors: comment.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
  end

  private

  def comment_params
    params
      .require(:comment)
      .permit(:title, :description)
      .merge(product_id: params[:product_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)

    unless comment.save
      flash[:errors] = comment.errors
    end

    redirect_to product_path(params[:product_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy

    redirect_to product_path(params[:product_id])
  end

  private

  def comment_params
    params
      .require(:comment)
      .permit(:title, :description)
      .merge(product_id: params[:product_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @comment = Comment.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def serialize(template, options = {})
    JbuilderTemplate
      .new(self) { |json| json.partial! template, options }.attributes!
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VuexTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_tag do %>
      I18n.locale = "<%= I18n.locale %>";
      I18n.translations = <%= raw I18n::JS.filtered_translations.to_json %>;;
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% props = { products: serialize('serializers/products', products: @products ) }.to_json %>

<div class="vue-products" data-props="<%= props %>"></div>

app/views/products/show.html.erb
<h1 class="my-4">
  <%= @product.name %>
</h1>
<p>
  <%= link_to t('products.back'), products_path %>
</p>

<div class="row">
  <div class="col-md-8">
    <%= image_tag @product.image, class: 'img-fluid' %>
  </div>

  <div class="col-md-4">
    <h3 class="my-3">Project Description</h3>
    <p>
      <%= @product.description %>
    </p>
  </div>
</div>

<%
  props = {
    product: serialize('serializers/product', product: @product)
  }.to_json
%>

<div class="vue-comments" data-props="<%= props %>"></div>

<div class="vue-comment-form" data-props="<%= props %>"></div>

app/views/shared/_comments.html.erb
<h4 class="my-4">Comments</h4>

<div class="row">
  <% if comments.any? %>
    <% comments.each do |comment| %>
      <div class="col-md-12 my-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= comment.title %></h5>
            <p class="card-text"><%= comment.description %></p>

            <%= form_for [product, comment], method: :delete do |form| %>
              <%= form.submit t('comments.form.delete'), class: 'btn btn-sm btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col-md-12">
      <p>
        <%= t('comments.empty') %>
      </p>
    </div>
  <% end %>
</div>